// 세계 수도송 1탄 순서 그대로. 오답 보기는 이 목록 안의 다른 수도에서 무작위로 2개 뽑는다.
// 주관식 채점 시 인정하는 다른 표기 (띄어쓰기·대소문자는 자동 무시)
window.CAPITAL_ALIASES = {
  "워싱턴DC": ["워싱턴", "워싱턴디씨", "워싱턴D.C.", "워싱톤"],
  "멕시코시티": ["멕시코시티", "멕시코"],
  "뉴델리": ["뉴델리", "델리"],
  "베이징": ["베이징", "북경"],
  "도쿄": ["도쿄", "동경"],
  "마드리드": ["마드리드", "마드리드"],
  "암스테르담": ["암스테르담", "암스텔담"],
  "카트만두": ["카트만두", "캇만두"],
  "브라질리아": ["브라질리아", "브라질리야"],
  "몬테비데오": ["몬테비데오", "몬테비디오"],
  "네피도": ["네피도", "네피더"],
  "하노이": ["하노이"],
  "다카르": ["다카르", "다카"],
  "아부자": ["아부자"],
};
window.QUIZ_ITEMS = [
  { c: "아시아", country: "한국", answer: "서울" },
  { c: "아시아", country: "일본", answer: "도쿄" },
  { c: "아시아", country: "싱가포르", answer: "싱가포르" },
  { c: "아시아", country: "중국", answer: "베이징" },
  { c: "아시아", country: "태국", answer: "방콕" },
  { c: "아시아", country: "네팔", answer: "카트만두" },
  { c: "아시아", country: "인도", answer: "뉴델리" },
  { c: "아시아", country: "미얀마", answer: "네피도" },
  { c: "아시아", country: "베트남", answer: "하노이" },
  { c: "아시아", country: "필리핀", answer: "마닐라" },

  { c: "유럽", country: "프랑스", answer: "파리" },
  { c: "유럽", country: "독일", answer: "베를린" },
  { c: "유럽", country: "이탈리아", answer: "로마" },
  { c: "유럽", country: "스위스", answer: "베른" },
  { c: "유럽", country: "영국", answer: "런던" },
  { c: "유럽", country: "스페인", answer: "마드리드" },
  { c: "유럽", country: "그리스", answer: "아테네" },
  { c: "유럽", country: "체코", answer: "프라하" },
  { c: "유럽", country: "네덜란드", answer: "암스테르담" },
  { c: "유럽", country: "러시아", answer: "모스크바" },

  { c: "아메리카", country: "캐나다", answer: "오타와" },
  { c: "아메리카", country: "쿠바", answer: "아바나" },
  { c: "아메리카", country: "미국", answer: "워싱턴DC" },
  { c: "아메리카", country: "멕시코", answer: "멕시코시티" },
  { c: "아메리카", country: "브라질", answer: "브라질리아" },
  { c: "아메리카", country: "칠레", answer: "산티아고" },
  { c: "아메리카", country: "우루과이", answer: "몬테비데오" },
  { c: "아메리카", country: "페루", answer: "리마" },

  { c: "오세아니아", country: "호주", answer: "캔버라" },
  { c: "오세아니아", country: "뉴질랜드", answer: "웰링턴" },

  { c: "아프리카", country: "우간다", answer: "캄팔라" },
  { c: "아프리카", country: "가나", answer: "아크라" },
  { c: "아프리카", country: "세네갈", answer: "다카르" },
  { c: "아프리카", country: "모로코", answer: "라바트" },
  { c: "아프리카", country: "나이지리아", answer: "아부자" },
  { c: "아프리카", country: "케냐", answer: "나이로비" },
];
